apiVersion: v1
kind: ConfigMap
metadata:
  name: cinema-tickets-db-config
  namespace: cinema-tickets
  labels:
    app.kubernetes.io/name: cinema-tickets
    app.kubernetes.io/part-of: cinema-tickets
    app.kubernetes.io/component: database
data:
  POSTGRES_DB: "cinema"