apiVersion: v1
kind: Secret
metadata:
  name: cinema-tickets-db-secret
  namespace: cinema-tickets
  labels:
    app.kubernetes.io/name: cinema-tickets
    app.kubernetes.io/part-of: cinema-tickets
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "change_me"